### PR TITLE
chore: use original brand color for discord badge

### PR DESCRIPTION
**Pull request by okineadev**

### CODE REVIEW

**Comment by okineadev** [comment]
merge pliz

**Comment by nhedger** [comment]
> merge pliz

This a volunteer project. Please don't put pressure on maintainers. We merge if and when appropriate.

**Comment by okineadev** [comment]
> > merge pliz
> 
> This a volunteer project. Please don't put pressure on maintainers. We merge if and when appropriate.

You call this pressing? Seriously? 😂
I saw that one maintainer approved this PR but didn't merge it, so I asked him to merge it.

Dude, don't exaggerate.

**Comment by arendjr** [comment]
@okineadev I also commented on your messages on Discord. Yes, it is considered pressing.

Please be respectful to our maintainers, as the tone in your last message can be seen as very disrespectful. Please consider this a warning.

**Comment by okineadev** [comment]
> @okineadev I also commented on your messages on Discord. Yes, it is considered pressing.
> 
> Please be respectful to our maintainers, as the tone in your last message can be seen as very disrespectful. Please consider this a warning.

😂😂😂

**Comment by okineadev** [comment]
> @okineadev I also commented on your messages on Discord. Yes, it is considered pressing.
> 
> Please be respectful to our maintainers, as the tone in your last message can be seen as very disrespectful. Please consider this a warning.

I'm sorry if I offended you, it really hurts, don't cry...

**Pull request merged**
