### PR TITLE
feat: v3

### PR DESCRIPTION
**Pull request by nhedger**
### Projects

This new version introduces the concept of projects, which aims to provide a comprehensive solution for running multiple independent Biome LSP sessions across different workspace folders or even individual folders within a mono-repository layout.

Unless explicitly told otherwise, the extension will automatically and transparently create a single project for each workspace folder present in the workspace.

This new version introduces the `biome.projects` configuration setting to support more complex use cases such as mono-repositories. This setting may be used to explicitly define projects at the *workspace* level or at the *workspace folder* level. This setting is ignored when defined globally, as it makes no sense in this case.

In summary, projects open up the possibility of running different versions of Biome in different parts of the user’s code base, with the possibility to use dedicated configuration files if necessary.

### Global LSP session

Up until now, the extension used the first available LSP to provide Biome support to *Untitled* files (files that haven’t yet been saved to disk). While usually not an issue in single-root workspaces, this approach is less ideal in multi-root workspaces where the LSP you’d get depended on the order in which the workspace folders had been opened/added.

To tackle this issue, the extension introduces an on-demand global LSP session dedicated to providing Biome features to *Untitled* files, and files opened in *single-file mode*. In workspace mode, this session is automatically destroyed to preserve resources once no more *Untitled* files are opened in the editor.

### Platform-specific binaries

The new `biome.lsp.bin` configuration setting, which replaces `biome.bin` brings support for platform-specific binaries. Users will be able to specify the value either a string, or an object that maps platforms to their respective binaries.

**Using a string**

```json
{
  "biome.lsp.bin": "/path/to/biome"
}
```

**Using an object**

```json
{
  "biome.lsp.bin": {
    "linux-x64": "/path/to/biome",
    "linux-arm64-musl": "/path/to/biome",
    "darwin-arm64": "/path/to/biome",
    "win32-x64": "/path/to/biome.exe"
  }
}
```

### CODE REVIEW

**Comment by Araxeus** [comment]
Sorry to intrude here, but could you make sure https://github.com/biomejs/biome/pull/3649#issuecomment-2286072068 is fixed in v3?

> The original issue was triggered when **a single file** was opened by a single client. When this occurs, the client can't pass `rootUri` or `workspaceFolders`

So if I open vscode with `C://git/mysnippets/snippet.js` the workdir should be `C://git/mysnippets`

(that way `biome check "C://git/mysnippets/snippet.js"` will have the same output as vscode)

**Comment by ffMathy** [comment]
Very cool. When does this release?

**Comment by nemchik** [comment]
> Very cool. When does this release?

When it's ready.

**Comment by nhedger** [comment]
Feel free to try out the nightly. It's still a bit rough around the edges though!

If you see anything suspicious let me know.

**Comment by ffMathy** [comment]
Sure, will do! Very excited about this release. Can't wait (in case that wasn't obvious already) ❤️ 😄

**Comment by raix** [comment]
@nhedger Thank you, been following 💪  and will give it a spin on PlatformPlatform ❤️ 🚀

**Comment by nathggns** [comment]
Where's the best place to report issues with this? Relative paths don't seem to be working right now

**Comment by nhedger** [comment]
> Where's the best place to report issues with this? Relative paths don't seem to be working right now

An issue in this repo is fine, thanks !

**Comment by ffMathy** [comment]
Can we release it as a pre-release VS Code extension, so it's easier to consume and try out?

**Comment by nhedger** [comment]
Already has been. Pre release channel is v3

**Comment by ffMathy** [comment]
I get the following in the Biome output window:

```
2024-09-04 07:26:25.373 [info] Biome extension activated
2024-09-04 07:26:25.864 [error] Failed to start Biome extension
2024-09-04 07:26:25.864 [info] Biome extension started
```

**Pull request merged**
