### PR TITLE
docs: improve contribution guide

### LINKED ISSUE #147: 🐛 Missing information in the contributing section
### Extension version

main

### Biome version

main

### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux

### Description

The current `CONTRIBUTING.md` document doesn't explain how a contributor can bundle the VSCode extension, and it doesn't explain how to launch VSCode with the bundled extension. 

### Steps to reproduce

1. Open the document `CONTRIBUTING.md`
2. Check the `Development` header
3. It mentions a watch mode for debugging, but it's unclear how it works. I pressed in `F5`, but it didn't do anything

### Expected behavior

I would expect more information for people who aren't accustomed to the developments of the project

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

### Logs

_No response_

### PR DESCRIPTION
**Pull request by nhedger**
### Summary

Improves the contribution guide

### Description

Improves the contribution guide by explaining how the extension can be built locally.

### Related Issue

This PR closes #147

### CODE REVIEW

**Comment by ematipico** [comment]
Internally there's a command called `pack:dev` that does bundling, compilation and installation, why can't we document this command instead?

**Comment by nhedger** [comment]
We can, I just assumed people would just run the app with the debug, as I do.

**Comment by ematipico** [comment]
Ok. Sorry if I'm being so dumb, but unfortunately I struggle to understand the flow.

So I open this repository with VSCode, then I click F5, open another project that uses the extension, and when I modify this source the other project will use the new compiled code?


Second thought: the contribution guide assumes that a person uses VSCode, but I use other editors, there's no F5 😅

**Comment by nhedger** [comment]
No problem, I'll try to explain this better.

First, the contribution guide assumes that you're using VS Code to develop the extension because it's the easiest way to debug it. We can definitely improve the guide to include instructions for user who don't use VS Code as their main editor, though.

When you open this repo with VS Code and press F5, VS Code will spawn a separate VS Code instance meant only for debugging. This separate instance does two things:

1. It disables all extensions
2. It loads the Biome extension being debugged (the watcher builds it in `out/`)

You can then use this separate instance to load any other project to test the behavior of the Biome extension on a real project.

Hope this clears it.

**Comment by ematipico** [comment]
That's way better, thank you!

**Comment by nhedger** [comment]
Will be overhauled as part of v3.

**Pull request closed without merging**
