### PR TITLE
feat: publish nightlies as pre-releases

### LINKED ISSUE #137: 📎 Publish nightlies as pre-releases instead of separate extension
### Summary

The stable and nightly versions of Biome are currently published as two separate extensions.

- `biomejs.biome` (stable)
- `biomejs.biome-nightly` (nightly)

One of the goals of publishing a nightly release of the extension is to allow early adopters to test new features and help us catch issues before they land in a stable release. In order to reduce friction, switching from the stable release to the nightly and vice-versa should be as straightforward as possible.

When I originally petitioned to split both releases into separate extensions, my hope was to avoid dealing with the fact that the VS Marketplace does not support SemVer. To cope with that limitation, extensions that publish pre-releases usually have a system in place that consists of publishing stable releases with an even-numbered minor version and pre-releases with an odd-numbered minor version.

- 2.**0**.0 (stable)
- 2.**1**.0 (pre-release)
- 2.**2**.0 (stable)

This has the effect of producing non-linear versions within a channel (`2.0.0` -> `2.2.0`), which is something I'm admittedly not a fan of. That being said, and [having discussed it among ourselves and with community members](https://github.com/biomejs/biome-vscode/discussions/123), we feel that the benefits of having a single extension with two release channels outweigh the cons.

- Easier to switch between _stable_ and _nightly_
- Users need to maintain only one set of settings
- Easier upgrade path
- No more conflicts between both versions

### Upgrade paths

- Users who subscribe to the stable release channel expect to be upgraded to the next stable version, not the next pre-release version.
- Users who subscribe to the pre-release channel expect to be upgraded to the next pre-release version, but won't mind being upgraded to the next stable release if there isn't yet a pre-release version available.

### Version numbers

To prevent confusion, **the version number of the latest stable release should always be higher than the latest pre-release**, even if this means that we end up with gaps.

For example, if we publish a pre-release (`2.1.0`), and some days later we publish another pre-release (`2.3.0`), the next stable release should not be `2.2.0`, but `2.4.0`.

### To do

- [x] Stop packaging nightly
- [x] Stop publishing nightly
- [x] Mark pre-releases with `vsce`
- [x] Refactor code meant to prevent conflicts with nightly
- [x] Use CI to ensure the version pattern matches the corresponding channel
- [x] Use CI to ensure stable version numbers are always higher than the version of the latest pre-release

### PR DESCRIPTION
**Pull request by nhedger**
### Summary

This PR changes the way we publish nightly (pre-release) versions.

### Description

Up until now, we published two distinct extension (`biomejs.biome` & `biomejs.biome-nightly`). This PR leverages VS Code's pre-release system to ship both stable and pre-releases under the same name, using a pre-release flag where appropriate.

#### Versions

The nightly versions are released with a version number based on the date and time.

- `{year}.{month}.{day}{hour}`, e.g. `2024.2.1719`

This way, they don't clash with the semver-like version used for the stable releases.

### Todo

- [ ] Ask the VS Code team to deprecate `biomejs.biome-nightly`

### Related Issue

This PR closes #137

### CODE REVIEW

**Comment by Malix-off** [comment]
Is there any ETA on the pre-release release?

**Comment by Malix-off** [comment]
By the way, it's possible to ask the VS code team to deprecate `biomejs.biome-nightly` with the added metadata that it's been replaced with `biomejs.biome`

**Comment by nhedger** [comment]
> Is there any ETA on the pre-release release?

Already published

**Comment by nhedger** [comment]
> By the way, it's possible to ask the VS code team to deprecate `biomejs.biome-nightly` with the added explicit metadata that it's been replaced with `biomejs.biome`

Yep. Already asked them.

**Pull request merged**
