### PR TITLE
chore: add renovate configuration

### LINKED ISSUE #197: Setup Renovate
We've started using Renovate in the other repositories, let's replace dependabot with Renovate here too.

### PR DESCRIPTION
**Pull request by AshutoshNanaware**
### Related Issue

This PR closes #197

### Checklist

- [ ] I have tested my changes on the following platforms:
  - [ ] Windows
  - [ ] Linux
  - [ ] macOS

### CODE REVIEW

**Comment by nhedger** [comment]
LGTM, thanks for your contribution!

**Comment by ematipico** [comment]
@AshutoshNanaware could you please look after this? https://github.com/biomejs/biome-vscode/pull/253#issuecomment-2199491432

**Comment by AshutoshNanaware** [comment]
@ematipico  sure.

**Comment by nhedger** [comment]
It's fixed @AshutoshNanaware.

**Pull request merged**
