### PR TITLE
chore: do not sync `biome.lspBin` by default

### PR DESCRIPTION
**Pull request by Malix-off**

### CODE REVIEW

**Comment by nhedger** [comment]
What is the rationale behind this change?

As far as I know, we haven't had any complaints regarding the syncing of this option. 

Not to say I'm against it; I'd just like to understand.

**Comment by Malix-off** [comment]
@nhedger

Hello Nicolas!

It is a common thing for all the vscode extensions i've seen so far to have binary path configuration contributions having `ignoreSync`, the rationale being that the binary path isn't guaranteed to be the same between devices.

**Comment by nhedger** [comment]
Thanks for the clarification.

If a user wanted to sync this setting anyway, is there a way for him to force it?

**Comment by Malix-off** [comment]
@nhedger
Absolutely!
`ignoreSync` is just to make it default [(documentation)](https://code.visualstudio.com/updates/v1_75#_ignore-a-setting-to-sync)
image

**Comment by nhedger** [comment]
Cool, thanks!

**Comment by Malix-Labs** [comment]
I couldn't find the difference between `ignoreSync` and the "machine" scope, so I asked for vscode's clarification (see https://github.com/microsoft/vscode-docs/issues/7638)

I might publish an update

**Pull request merged**
